# Generated by Django 5.2.7 on 2026-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='Mon-Fri', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time',
            field=models.CharField(default='9 AM - 5 PM', max_length=100),
        ),
    ]
