# Generated by Django 5.2.7 on 2026-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
